### ISSUE TITLE
Needed to install a bunch of nltk modules

### ISSUE THREAD

**Issue by smb-apache** [johan456789/yaktoa#3]
First of all I finally got around to trying this out, I was just so burnt out the last time that it put me off these Kindle to Anki projects forever... but I tried it out now and it works beautifully! No formatting issues like previous ones and actually pulling dictionary definitions. It's a miracle.

I followed the instructions but I had to open a python shell, import nltk, and install a bunch of NLTK modules, the three I believe were:

nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('punkt')

Just thought I'd share my experience in case anyone else comes across your project and runs into the same issues as me.

Thanks again for sharing!

**Comment by johan456789** [comment]
> First of all I finally got around to trying this out, I was just so burnt out the last time that it put me off these Kindle to Anki projects forever... but I tried it out now and it works beautifully! No formatting issues like previous ones and actually pulling dictionary definitions. It's a miracle.

I'm glad you find my project useful. I jumped through the same hoops and eventually decided that it's easier to make one myself.

> I followed the instructions but I had to open a python shell, import nltk, and install a bunch of NLTK modules, the three I believe were:

I don't know why I don't need those steps. I will leave this issue open and add those steps in the documentation if later finding them indeed necessary.
