### ISSUE TITLE
cred.py is missing

### ISSUE THREAD

**Issue by smb-apache** [johan456789/yaktoa#4]
Thought it'd be worth mentioning that the cred.py file is missing, I filled in the blanks but maybe someone coming across this might be looking for it and not know what to do?

For anyone wondering, I needed to create a cred.py file, put it in the same directory, and put in:

app_id, app_key = "<app id here>", "<api key here>"

**Comment by johan456789** [comment]
Added `cred.py`. Thanks for the notice.
